### ISSUE TITLE
不知该在哪里定义真实 openai api key

### ISSUE THREAD

**Issue by aoaim** [yinm0591/cf-openai-with-sub-account-proxy#1]
开发者你好，我今天尝试搭建项目的过程中发现，即使定义了真实的 openai api key 后依旧报错 `Missing API key`，不知该如何修改：

```
const subKey = {
    'key': ['sk-xxx在openai官网上获得的真实key', null]
};
```

查看[早期记录](https://github.com/yinm0591/cf-openai-with-sub-account-proxy/commit/c95dd1cb8ff746f237c2a4a18ccb711c191a96cb)发现代码中需要额外定义 `OpenAI_Key` 和 `OpenAI_Org_ID`，但在现在的版本中取消了，似乎是归在了 `subKey` 中，但不知该如何填写。

在 cf worker 的控制台显示
<img width="551" alt="image" src="https://github.com/yinm0591/cf-openai-with-sub-account-proxy/assets/48897696/c145d82a-f275-4e88-aeba-0e3fbdfc18a5">

在 OpenCat 中填写了和 `subKey` 中相同的 key 后显示
<img width="566" alt="image" src="https://github.com/yinm0591/cf-openai-with-sub-account-proxy/assets/48897696/cc9333ae-a0fa-4b86-b27a-36c718366d52">

希望得到你的帮助，谢谢！

**Comment by yinm0591** [comment]
opencat设置界面有2个验证按钮，第一个按钮是发给openai.com官网的，你要点击第二个验证按钮

**Comment by aoaim** [comment]
对，我就是在第一个api key填写真实key然后在自定义api url填写后选择的第二个验证

**Comment by yinm0591** [comment]
你的openai key的写法是对的。你检查一下自定义key是否和opencat输入一致（前后不能有多余的空格）。建议先定义一个简单的key，调通后再改成一个复杂的key

**Comment by aoaim** [comment]
在 `subKey` 下先写真实的 key，再加上自定义的 key ，如，

```
const subKey = {
    'key': ['sk-xxx在openai官网上获得的真实key', null]，
    'custom_key1': ['sk-ABCDEFGHIJKLMN', null]，
    'custom_key1': ['sk-ABCDEFGHIJKLMN', null]，
};
```

然后在 OpenCat 等客户端的 URL 处填写 cf worker 的 url，key 处填写 custom_key1。

是这样的么？

**Comment by yinm0591** [comment]
const subKey = {
    'custom_key1': ['sk-ABCDEFGHIJKLMN', null]
};

opencat填cf worker的域名，key用custom_key1

**Comment by aoaim** [comment]
那我应该在 cf worker 的哪里定义从 OpenAI 网站获得的真实 key 呢？

**Comment by yinm0591** [comment]
sk-ABCDEFGHIJKLMN 替换成真实的openai key

代码注释里写了格式的：
My_API_Sub_Keys : [OpenAI_API_Key, OpenAI_Organization_ID]
